### ISSUE TITLE
Error in minify

### ISSUE THREAD

**Issue by daycry** [michalsn/minifier#5]
It doesn't minify correctly, when I launch the minify command the response is as follows:

![image](https://user-images.githubusercontent.com/7590335/136550671-43a7d6bf-93ff-4323-bb61-8587880e64bd.png)

In main.min.css file

**Comment by daycry** [comment]
It would be interesting to be able to choose the final path of the minified ones, because it does not make sense that the minified ones enter the same path.

I will commit some changes, to solve that problem.

**Comment by michalsn** [comment]
Any updates on this issue? Were you able to fix it? Or is it a false alarm?

**Comment by michalsn** [comment]
I'm closing this, since it doesn't seem to be an issue, but feel free to continue the conversation - especially if you can provide more info. Thanks.
