### ISSUE TITLE
why use $dirMinJs and $dirMinCss make emptyFolder()

### ISSUE THREAD

**Issue by paul45** [michalsn/minifier#7]
The new release is a good idea with $dirMinJs and $dirMinCss

but why use $dirMinJs and $dirMinCss make emptyFolder()

for me i have many minified files in my folder and i dont want delet all when one file is update

**Comment by michalsn** [comment]
Fair point. Would you like to send a PR to fix this?

**Comment by paul45** [comment]
maybe just remove emptyFolder($minDir) function ?

`elseif ($dir !== $minDir)
        {
            $this->emptyFolder($minDir);
        }`

**Comment by michalsn** [comment]
Fixed in [v1.4.0](https://github.com/michalsn/minifier/releases/tag/v1.4.0)
